sudo: required

services:
  - docker

before_install:
  - docker pull quasarhq/cross-compiler:android-arm
  - docker pull quasarhq/cross-compiler:android-x64
  - docker pull quasarhq/cross-compiler:darwin-x64
  - docker pull quasarhq/cross-compiler:linux-x86
  - docker pull quasarhq/cross-compiler:linux-x64
  - docker pull quasarhq/cross-compiler:linux-arm
  - docker pull quasarhq/cross-compiler:windows-x86
  - docker pull quasarhq/cross-compiler:windows-x64
  - make env PLATFORM=android-arm
  - make env PLATFORM=android-x64
  - make env PLATFORM=darwin-x64
  - make env PLATFORM=linux-x86
  - make env PLATFORM=linux-x64
  - make env PLATFORM=linux-arm
  - make env PLATFORM=windows-x86
  - make env PLATFORM=windows-x64

script:
  - make android-arm
  - make android-x64
  - make darwin-x64
  - make linux-x86
  - make linux-x64
  - make linux-arm
  - make windows-x86
  - make windows-x64
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make push || true'
